server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: url-proxy-1
          uri: https://blog.csdn.net
          predicates:
            - Path = /csdn
  codec:
    max-in-memory-size: 5MB  # 修复拦截POST请求后内存超出缓冲区

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG